# Modern Docker Compose V2+ configuration
# Uses compose.yml as per current Docker standards
# Run with: docker compose up -d

name: wazuh-mcp-server

services:
  wazuh-mcp-server:
    build: .
    container_name: wazuh-mcp-server
    restart: unless-stopped
    init: true
    
    # Load configuration from file
    env_file:
      - ./config/wazuh.env
    
    # Transport mode - defaults to HTTP/SSE
    environment:
      MCP_TRANSPORT: ${MCP_TRANSPORT:-http}
      MCP_HOST: ${MCP_HOST:-0.0.0.0}
      MCP_PORT: ${MCP_PORT:-3000}
    
    # Port mapping for HTTP/SSE mode (default)
    ports:
      - "${MCP_PORT:-3000}:3000"
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "from src.wazuh_mcp_server.config import WazuhConfig; WazuhConfig.from_env()"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    
    # For STDIO mode (when MCP_TRANSPORT=stdio)
    stdin_open: true
    tty: true