# Docker Compose for Wazuh MCP Server v3.0.0 - Production Core
# =============================================================
# Minimal production-grade configuration focused on core MCP functionality
# No monitoring, no nice-to-have features - just production MCP

services:
  wazuh-mcp-server:
    # Production-ready build from source
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-linux/amd64}
        TARGETPLATFORM: ${TARGETPLATFORM:-linux/amd64}
    container_name: wazuh-mcp-server
    restart: unless-stopped
    
    # Production security settings
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    user: "1000:1000"
    
    # Network - single port for MCP
    ports:
      - "${MCP_SERVER_PORT:-8443}:8443"  # MCP Server HTTPS/SSE
    
    # Core environment variables only
    environment:
      # Server configuration
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8443
      - MCP_SERVER_MODE=${MCP_SERVER_MODE:-auto}
      - MCP_TRANSPORT=${MCP_TRANSPORT:-sse}
      
      # Wazuh API configuration (REQUIRED)
      - WAZUH_API_URL=${WAZUH_API_URL}
      - WAZUH_API_USERNAME=${WAZUH_API_USERNAME}
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}
      - WAZUH_API_VERIFY_SSL=${WAZUH_API_VERIFY_SSL:-true}
      
      # Production security
      - OAUTH_ENABLED=${OAUTH_ENABLED:-true}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-auto-generate}
      
      # Production logging
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - LOG_FORMAT=json
      
      # Disable non-essential features
      - ENABLE_METRICS=false
      - REDIS_ENABLED=false
      
      # Performance for production
      - MAX_CONNECTIONS=${MAX_CONNECTIONS:-1000}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
      - WORKER_PROCESSES=${WORKER_PROCESSES:-4}
      
      # Self-contained mode
      - SELF_CONTAINED=true
      - AUTO_GENERATE_CONFIG=true
      - PRESERVE_V2_COMPATIBILITY=true
      
    # Minimal volumes - only essential data
    volumes:
      - wazuh-mcp-config:/app/config:rw
      - wazuh-mcp-logs:/app/logs:rw
      - wazuh-mcp-data:/app/data:rw
      - /tmp:/tmp:rw  # Required for stdio mode
    
    # Production health check
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Production logging
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    
    # Isolated network
    networks:
      - wazuh-mcp-network

# Production network
networks:
  wazuh-mcp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

# Essential volumes only
volumes:
  wazuh-mcp-config:
    driver: local
  wazuh-mcp-logs:
    driver: local
  wazuh-mcp-data:
    driver: local